apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infrastructure-sync.yaml
- notification-receiver.yaml
- receiver-service.yaml
- webhook-token.yaml
# - image-update-automation.yaml
- applications-sync.yaml