apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cloud-native-weather-dotnet
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloud-native-weather-dotnet
  validation: client
  targetNamespace: weather-dotnet
  images:
    - name: cloud-native-weather-dotnet
      newName: ghcr.io/qaware/cloud-native-weather-dotnet # {"$imagepolicy": "flux-system:cloud-native-weather-dotnet:name"}
      newTag: 1.2.0 # {"$imagepolicy": "flux-system:cloud-native-weather-dotnet:tag"}
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: weather-service
      spec:
        replicas: 2
    - apiVersion: v1
      kind: Service
      metadata:
        name: weather-service
      spec:
        type: LoadBalancer
