apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cne01.yaml
- cne02.yaml
- cne03.yaml
- cne04.yaml
- cne05.yaml
- cne06.yaml
- cne07.yaml
- cne08.yaml
- cne09.yaml
- cne10.yaml
- cne11.yaml
- cne12.yaml
#- cne13.yaml
#- cne14.yaml
#- cne15.yaml
#- cne16.yaml
#- cne17.yaml
#- cne18.yaml
#- cne19.yaml
#- cne20.yaml

